### ISSUE TITLE
set-properties test doesn't build with GHC 8.6

### ISSUE THREAD

**Issue by osa1** [haskell/containers#570]
Tried with --allow-newer so perhaps this first needs an update in QuickCheck. Error:

```
tests/set-properties.hs:257:7: error:
    • No instance for (Control.Monad.Fail.MonadFail Gen)
        arising from a do statement
        with the failable pattern ‘x : xs’
    • In a stmt of a 'do' block: x : xs <- get
      In the expression:
        do x : xs <- get
           put xs
           pure x
      In an equation for ‘step’:
          step
            = do x : xs <- get
                 put xs
                 pure x
    |
257 |       x : xs <- get
    |       ^^^^^^^^^^^^^
```
