### PR TITLE
Fix compilation of 'set-properties' test suite with GHC-8.6

### LINKED ISSUE #570: set-properties test doesn't build with GHC 8.6
Tried with --allow-newer so perhaps this first needs an update in QuickCheck. Error:

```
tests/set-properties.hs:257:7: error:
    • No instance for (Control.Monad.Fail.MonadFail Gen)
        arising from a do statement
        with the failable pattern ‘x : xs’
    • In a stmt of a 'do' block: x : xs <- get
      In the expression:
        do x : xs <- get
           put xs
           pure x
      In an equation for ‘step’:
          step
            = do x : xs <- get
                 put xs
                 pure x
    |
257 |       x : xs <- get
    |       ^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #570.

### CODE REVIEW

**Comment by treeowl** [comment]
Thanks!
