### PR TITLE
Make foldr' & friends more strict

### LINKED ISSUE #749: Strictness of `foldr'` and `foldl'`
To my surprise I found out that `foldr'` and `foldl'` are not as strict as I would think of.  They do not demand the result of every application of the accumulator function, instead they demand only when it is reaching the `Tip`. That's ok when folding to something like an `Int`, but let's look what happens when we fold to a list.

```
> import Data.Map (Map)
> import qualified Data.Map as Map
> x = Map.fromList $ (\x -> (x,x)) `map` [0..10] :: Map Int Int
> y = Map.foldr' (:) [] x :: [Int]
> y `seq` ()
()
> :sprint y
y = 0 : _
```
If the accumulator `:` was demanded after every application demanding `y` would force the spine of the list not just the first element.  And indeed [the implementation](https://hackage.haskell.org/package/containers-0.6.4.1/docs/src/Data.Map.Internal.html#foldr') reveals that this is indeed the case.

I also wrote a small [gist](https://gist.github.com/coot/4bda8ec91fbf5c22b3d521170d3b98dc) to play with this. It gives the following outpu for `Map.foldr'`, `Map.foldr` and then forcing the spine of the list with `length`, and a custom `foldr'` which demand every application of the accumulator:
```
*** Map.foldr' ***

"_ind (_bh (I# 1 : _thunk _fun (I# 2 : _thunk _fun (I# 4 : _thunk _fun ([] 5032544) (Bin (I# 8) (I# 8) (B
in (I# 6) (I# 6) (Bin (I# 5) (I# 5) (Tip 4457056) (Tip 4457056) 1) (Bin (I# 7) (I# 7) (Tip 4457056) (Tip 
4457056) 1) 3) (Bin (I# 9) (I# 9) (Tip 4457056) (Bin (I# 10) (I# 10) (Tip 4457056) (Tip 4457056) 1) 2) 6)
) (Bin (I# 3) (I# 3) (Tip 4457056) (Tip 4457056) 1)) (Tip 4457056)))"

*** Map.foldr' & seq ***

"_ind (_bh (I# 1 : _bh (I# 2 : _bh (I# 3 : _bh (I# 4 : _bh (I# 5 : _bh (I# 6 : _bh (I# 7 : _bh (I# 8 : _b
h (I# 9 : _bh (I# 10 : _bh ([] 5032544))))))))))))"

*** foldr' ***
"_ind (_bh (I# 1 : I# 2 : I# 3 : I# 4 : I# 5 : I# 6 : I# 7 : I# 8 : I# 9 : I# 10 : [] 5032544))"

```

As you can see `Map.foldr'` retains the original map, the other two don't.

The haddock of `foldr'` sais:

> Each application of the operator is evaluated before using the result in the next application.

I think that either the documentation should be more accurate about strictness of `foldr'` and `foldl'` (which is also affected in the same way), or the implementation should be amended. 

This was discovered when working on https://github.com/input-output-hk/ouroboros-network/pull/2631

### PR DESCRIPTION
**Pull request by coot**
Fixes #749

There are no tests that checks that `foldr'` or `foldl'` are strict.  The
[nothunks](https://hackage.haskell.org/package/nothunks) library could be used to test it.

- Make Data.Map.foldr' and Data.Map.foldl' more strict
- Make foldrWithKey' and foldlWithKey' more strict

### CODE REVIEW

**Comment by sjakobi** [comment]
LGTM so far. Tests would be good to have indeed. I'm curious what these would look like with `nothunks` – I haven't used that package yet.

**Comment by coot** [comment]
I have troubles with safe haskell. I double checked that `-fpackage-trust` is not passed to `ghc`. I use `cabal-3.4.0.0` to build with `ghc-8.10.4`. Any clues?
```
src/Data/IntMap/Lazy.hs:242:1: error:
    Data.IntMap.Internal.DeprecatedDebug: Can't be safely imported!
    The module itself isn't safe.
    |
242 | import Data.IntMap.Internal.DeprecatedDebug
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by sjakobi** [comment]
@coot I haven't been able to reproduce the issue so far. Which command are you using at which commit?

**Comment by coot** [comment]
I can reproduce it on current `master`7fb91ca53b1aca7c077b36a0c1f8f785d177da34 with  `cabal build lib:containers`.

**Comment by coot** [comment]
Interestingly, `cabal-3.2.0.0` works just fine, so at least I am unblocked here.

**Comment by coot** [comment]
I pushed four quickcheck test using [nothunks](https://hackage.haskell.org/package/nothunks) library. I also checked that `master` branch would fail these tests. Note that `nothunks` is only available sing `ghc-8.6`, so there's a bit of clutter with `cpp` flags.

The problem with safe-haskell turned out to be that usage of a compiler plugin ([ghc-tags-plugin](https://hackage.haskell.org/package/ghc-tags-plugin)) that I use locally; bypassing `-fplugin-trustworthy` one can make safe haskell happy again.

File: containers-tests/tests/map-strictness.hs [hunk 1]
```diff
@@ -82,6 +94,35 @@ pInsertLookupWithKeyValueStrict f k v m
...
+  where
+    !r = M.foldrWithKey' (\_ a as -> a : as) [] m
+#endif
+
+#if __GLASGOW_HASKELL__ >= 806
+pStrictFoldlWithKey' :: Map Int Int -> Property
+pStrictFoldlWithKey' m = ioProperty $ isNothing <$> noThunks [] r
+  where
+    !r = M.foldlWithKey' (\as _ a -> a : as) [] m
+#endif
```
Comment (sjakobi) [inline containers-tests/tests/map-strictness.hs:124]: Is there an advantage to having one CPP conditional per property? It seems to me that a single one for all of them would be sufficient.

Comment (coot) [reply containers-tests/tests/map-strictness.hs:124]: I prefer short `#if`'s over long ones that are easier to miss when reading the code.

Comment (sjakobi) [reply containers-tests/tests/map-strictness.hs:124]: Good point.

File: containers-tests/tests/map-strictness.hs [hunk 2]
```diff
@@ -82,6 +94,35 @@ pInsertLookupWithKeyValueStrict f k v m
                      not (isBottom $ M.insertLookupWithKey (const3 1) k bottom m)
     | otherwise    = isBottom $ M.insertLookupWithKey (apply3 f) k bottom m
 
+#if __GLASGOW_HASKELL__ >= 806
+pStrictFoldr' :: Map Int Int -> Property
+pStrictFoldr' m = ioProperty $ isNothing <$> noThunks [] r
```
Comment (sjakobi) [inline containers-tests/tests/map-strictness.hs:99]: Could you turn this `isNothing <$> noThunks` pattern into a little helper?

**Review by sjakobi — COMMENTED** [review]
Looks good so far! :)

Would you mind adding properties (and possibly fixes) for `Data.Set.fold{l,r}'` too?

File: containers-tests/tests/map-strictness.hs (hunk 2 above)
Comment (coot) [reply containers-tests/tests/map-strictness.hs]: Done

**Comment by coot** [comment]
I'll look into `Set`, `IntMap` and `IntSet` the other day.

**Comment by coot** [comment]
@sjakobi done, `Set` operations needed to be fixed, but `IntSet` and `IntMap` where fine. I restructured the commit history, it should be nicer both to review commit by commit and give a nicer history once it's merged.

File: containers/src/Utils/NoThunks.hs [hunk 3]
```diff
@@ -0,0 +1,15 @@
+module Utils.NoThunks (whnfHasNoThunks) where
```
Comment (sjakobi) [inline containers/src/Utils/NoThunks.hs:1]: I think this file should be in `containers-tests/tests/Utils/`.

File: containers-tests/tests/intset-strictness.hs [hunk 4]
```diff
@@ -1,13 +1,31 @@
...
+#endif
+
+
+{--------------------------------------------------------------------
+  Arbitrary, reasonably balanced trees
+--------------------------------------------------------------------}
+instance Arbitrary IntSet where
+  arbitrary = do{ xs <- arbitrary
+                ; return (fromList xs)
+                }
```
Comment (sjakobi) [inline containers-tests/tests/intset-strictness.hs:27]: It's a bit unfortunate that this instance is duplicated. We can fix this when we eventually merge the various testsuites into one.

File: containers/src/Utils/NoThunks.hs (hunk 3 above)
Comment (coot) [reply containers/src/Utils/NoThunks.hs:1]: Yes, it's ought to be there.

Comment (coot) [reply containers/src/Utils/NoThunks.hs]: I put it under `containers-tests/src` which is the only directory in `hs-source-dirs` of `containers-test:lib:containers-test`.

Comment (sjakobi) [reply containers/src/Utils/NoThunks.hs]: `containers-tests/src` is a symlink to `containers/src`, i.e. not a good place for test things. Why not put it next to `Utils.IsUnit`?!

Comment (coot) [reply containers/src/Utils/NoThunks.hs:1]: I just realised this, quite surprising. I'll put it next to `Utils.IsUnit`.

Comment (coot) [reply containers/src/Utils/NoThunks.hs:1]: Done.

File: containers-tests/tests/intset-strictness.hs (hunk 4 above)
Comment (sjakobi) [reply containers-tests/tests/intset-strictness.hs:27]: I believe this instance needs to be moved behind CPP as well. With GHC < 8.6, CI reports:

```
tests/intset-strictness.hs:24:10: error:
    Not in scope: type constructor or class ‘Arbitrary’
   |
24 | instance Arbitrary IntSet where
   |          ^^^^^^^^^
```

**Comment by sjakobi** [comment]
It would also be good to check that the benchmarks don't regress more than expected. I guess something one the ~10% range would be acceptable, but I don't have any clear expectations on how this patch would affect perf.

**Comment by treeowl** [comment]
> It would also be good to check that the benchmarks don't regress more than expected. I guess something one the ~10% range would be acceptable, but I don't have any clear expectations on how this patch would affect perf.

I think we should expect better perf in reasonable circumstances.

**Comment by coot** [comment]
As expected, more strict version performs slightly better:

# Map

#### Version from this PR

```
benchmarking foldlWithKey' ... 
benchmarked foldlWithKey'
time                 27.76 μs   (27.15 μs .. 28.34 μs)
                     0.996 R²   (0.992 R² .. 0.998 R²)
mean                 27.08 μs   (26.84 μs .. 27.43 μs)
std dev              964.2 ns   (720.7 ns .. 1.350 μs)
variance introduced by outliers: 18% (moderately inflated)

benchmarking foldrWithKey' ... 
benchmarked foldrWithKey'
time                 74.02 ns   (73.01 ns .. 75.82 ns)
                     0.998 R²   (0.994 R² .. 1.000 R²)
mean                 73.14 ns   (72.91 ns .. 73.80 ns)
std dev              1.245 ns   (434.3 ps .. 2.625 ns)
```

#### Unmodified:
```
benchmarking foldlWithKey' ... 
benchmarked foldlWithKey'
time                 28.57 μs   (28.00 μs .. 29.35 μs)
                     0.991 R²   (0.979 R² .. 0.999 R²)
mean                 28.43 μs   (28.12 μs .. 28.99 μs)
std dev              1.358 μs   (729.0 ns .. 2.101 μs)
variance introduced by outliers: 27% (moderately inflated)

benchmarking foldrWithKey' ... 
benchmarked foldrWithKey'
time                 80.25 ns   (79.45 ns .. 81.13 ns)
                     0.998 R²   (0.996 R² .. 0.999 R²)
mean                 79.84 ns   (79.27 ns .. 80.68 ns)
std dev              2.184 ns   (1.572 ns .. 2.921 ns)
variance introduced by outliers: 11% (moderately inflated)
```

# Set
Most benchmarks are using `foldl'`:

#### Version from this PR

```
benchmarking member ... 
benchmarked member
time                 219.4 μs   (216.3 μs .. 222.6 μs)
                     0.999 R²   (0.997 R² .. 1.000 R²)
mean                 221.3 μs   (219.3 μs .. 225.3 μs)
std dev              10.25 μs   (5.408 μs .. 18.71 μs)
variance introduced by outliers: 28% (moderately inflated)

```

#### Unmodified

```benchmarking member ... 
benchmarked member
time                 237.1 μs   (231.5 μs .. 246.0 μs)
                     0.993 R²   (0.986 R² .. 0.999 R²)
mean                 234.3 μs   (232.1 μs .. 238.0 μs)
std dev              9.031 μs   (5.737 μs .. 15.46 μs)
variance introduced by outliers: 20% (moderately inflated)


```
# Benchmarking results

[map.txt](https://github.com/haskell/containers/files/6162820/map.txt)
[map-strict.txt](https://github.com/haskell/containers/files/6162821/map-strict.txt)
[set.txt](https://github.com/haskell/containers/files/6162822/set.txt)
[set-strict.txt](https://github.com/haskell/containers/files/6162823/set-strict.txt)

File: containers-tests/benchmarks/Map.hs [hunk 5]
```diff
@@ -72,8 +72,9 @@ main = do
         , bench "insertLookupWithKey' present" $ whnf (insLookupWithKey' elems_even) m_even
         , bench "mapWithKey" $ whnf (M.mapWithKey (+)) m
         , bench "foldlWithKey" $ whnf (ins elems) m
---         , bench "foldlWithKey'" $ whnf (M.foldlWithKey' sum 0) m
+        , bench "foldlWithKey'" $ whnf (M.foldlWithKey' sum 0) m
         , bench "foldrWithKey" $ whnf (M.foldrWithKey consPair []) m
+        , bench "foldrWithKey'" $ whnf (M.foldrWithKey consPair []) m
```
Comment (sjakobi) [inline containers-tests/benchmarks/Map.hs:77]:
```suggestion
        , bench "foldrWithKey'" $ whnf (M.foldrWithKey' consPair []) m
```

**Review by sjakobi — COMMENTED** [review]
One minor wibble left – LGTM apart from that.

File: containers-tests/benchmarks/Map.hs (hunk 5 above)
Comment (coot) [reply containers-tests/benchmarks/Map.hs]: Thanks,  it's squashed into previous commit.

**Review by sjakobi — APPROVED** [review]
Well, this turned out to be more work than I had initially expected. Thanks for doing it, @coot! :)

**Comment by treeowl** [comment]
Can you put benchmark results in a commit message? And seven commits seems like rather a lot. Can you reduce that? Would it be okay to squash it all, or are there some you want to preserve?

**Comment by coot** [comment]
@treeowl I'll squash them all.

**Comment by treeowl** [comment]
Whew! That was a marathon. Thanks!
