### ISSUE TITLE
containers-0.6.4.1 and 0.6.3.1 fail to build with GHC-9.6.1

### ISSUE THREAD

**Issue by phadej** [haskell/containers#942]
```
src/Data/Tree.hs:122:10: error: [GHC-39999]
    • Could not deduce ‘Ord (Tree a)’
        arising from the head of a quantified constraint
        arising from the superclasses of an instance declaration
      from the context: Ord a
        bound by a quantified context at src/Data/Tree.hs:122:10-18
    • In the instance declaration for ‘Ord1 Tree’
    |
122 | instance Ord1 Tree where
    |          ^^^^^^^^^
```

Please make Hackage revisions for affected versions.

**Comment by treeowl** [comment]
Done. Thanks. I see some very old `containers` versions (like 0.5.5.1) likely have invalid upper bounds, but I have no idea what the correct bounds may be. I suppose if someone is playing with `containers` from 2014 and modern GHC they may let us know what goes wrong.

**Comment by phadej** [comment]
Many older `containers` are restricted by `deepseq`, as e.g. 0.5.5.1 containers has `build-depends: deepseq >=1.2 && <1.3`. So you are good, indirectly though, but that's good enough.
